<h1>Social Media Marketing</h1>
<p class="lead align-content-center">Besides the <b>basic loading</b> of web site content (yours, or generated by us)
    onto social media platforms, we
    offer:
</p>
<div class="row  align-items-center">
    <div class="col">
        <p>A social media <b>campaign</b> with extra media uploaded daily on other platforms than the basic content
            platforms. These could be such platforms as Instagram, Facebook, or Twitter etc. Social media campaigns
            are
            normally used for launches of web sites, or products. Thus our package offers a three
            month campaign.
        </p>
    </div>
    <div class="col-lg-6 col-sm d-none d-md-block">
        <figure>
            <img src="/raw-assets/redundant%20stuff/socialmedia%20stuff/socialmedia/womenAtLaptop.jpg" class="img-fluid img-thumbnail"
                 alt="Working together to get things done">
        </figure>
    </div>
    <div class="col align-self-start align-self-md-center">
        <p>You may decide, however, to have the intensive use of several social media platforms throughout
            the year. We can offer this to you, with your choice of platforms etc., by negotiation.
        </p>
    </div>
</div>
<?php
$titleTag = "Social Media Marketing";
